name: Training cic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  PYTHON_VERSION: "3.11"
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  ECR_REPOSITORY: ${{ secrets.AWS_REPOSITORY }}
  SERVICE_NAME: "training-task-service"
  CLUSTER_NAME: "my-ecs-training"
  CONTAINER_NAME: "training-app"
  ECS_TASK_DEFINITION: "training-task.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      -  name: Cache Python dependencies
         uses: actions/cache@v4
         with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-   
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest # Install pytest
          pip install -r requirements.txt
          
      - name: Run tests with pytest
        run: pytest test_app.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}  

      - name: Upload static files to S3 bucket
  
        run: | 
          aws s3 sync . s3://${{ env.S3_BUCKET }}/ --delete

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      
      - name: Build image
        run: |
          # Use correct shell syntax for variable assignment (no spaces around '=')
          REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          REPO="${{ env.ECR_REPOSITORY }}"
          TAG="${{ github.sha }}"
          
          # Build with the commit SHA tag and tag again as 'latest'
          docker build -t $REGISTRY/$REPO:$TAG .
          docker tag $REGISTRY/$REPO:$TAG $REGISTRY/$REPO:latest

    
      - name: Push image to ECR
        run: |
          REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          REPO="${{ env.ECR_REPOSITORY }}"
          TAG="${{ github.sha }}"
          
          # Push both the SHA tag and the latest tag
          docker push $REGISTRY/$REPO:$TAG
          docker push $REGISTRY/$REPO:latest
          
      - name: Set Image URI Output
        id: set-output-uri
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

  deploy: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: configure AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_OIDC_ROLE_ARN}}
          aws-region: ${{env.AWS_REGION}}

      - name: Prepare the task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}  # e.g., task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image_uri: ${{ steps.build-and-push.outputs.image }} 

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.SERVICE_NAME }}
          cluster: ${{ env.CLUSTER_NAME }}

          wait-for-service-stability: "true"
